# Generated by Django 4.1.7 on 2023-04-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
